// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";

var Types = {};

var fragmentConverter = ({"__root":{"name":{"n":""},"image":{"n":""},"number":{"n":""},"weight":{"n":""},"weight_minimum":{"n":""},"weight_maximum":{"n":""},"height":{"n":""},"height_minimum":{"n":""},"height_maximum":{"n":""},"classification":{"n":""},"types":{"n":"","na":""},"resistant":{"n":"","na":""},"attacks":{"n":""},"attacks_fast":{"n":"","na":""},"attacks_fast_name":{"n":""},"attacks_fast_damage":{"n":""},"attacks_special":{"n":"","na":""},"attacks_special_name":{"n":""},"attacks_special_damage":{"n":""},"weaknesses":{"n":"","na":""},"fleeRate":{"n":""},"maxCP":{"n":""},"maxHP":{"n":""},"evolutions":{"n":"","na":""},"evolutions_name":{"n":""},"evolutions_image":{"n":""},"evolutionRequirements":{"n":""},"evolutionRequirements_amount":{"n":""},"evolutionRequirements_name":{"n":""}}});

function convertFragment(v) {
  return ReasonRelay._convertObj(v, fragmentConverter, undefined, undefined);
}

var Internal = {
  fragmentConverter: fragmentConverter,
  fragmentConverterMap: undefined,
  convertFragment: convertFragment
};

var Utils = {};

var node = ((function(){
var v0 = {
  "kind": "ScalarField",
  "alias": null,
  "name": "name",
  "args": null,
  "storageKey": null
},
v1 = {
  "kind": "ScalarField",
  "alias": null,
  "name": "image",
  "args": null,
  "storageKey": null
},
v2 = [
  {
    "kind": "ScalarField",
    "alias": null,
    "name": "minimum",
    "args": null,
    "storageKey": null
  },
  {
    "kind": "ScalarField",
    "alias": null,
    "name": "maximum",
    "args": null,
    "storageKey": null
  }
],
v3 = [
  (v0/*: any*/),
  {
    "kind": "ScalarField",
    "alias": null,
    "name": "damage",
    "args": null,
    "storageKey": null
  }
];
return {
  "kind": "Fragment",
  "name": "Pokemon_fragment",
  "type": "Pokemon",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    (v0/*: any*/),
    (v1/*: any*/),
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "number",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "weight",
      "storageKey": null,
      "args": null,
      "concreteType": "PokemonDimension",
      "plural": false,
      "selections": (v2/*: any*/)
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "height",
      "storageKey": null,
      "args": null,
      "concreteType": "PokemonDimension",
      "plural": false,
      "selections": (v2/*: any*/)
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "classification",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "types",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "resistant",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "attacks",
      "storageKey": null,
      "args": null,
      "concreteType": "PokemonAttack",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "name": "fast",
          "storageKey": null,
          "args": null,
          "concreteType": "Attack",
          "plural": true,
          "selections": (v3/*: any*/)
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "name": "special",
          "storageKey": null,
          "args": null,
          "concreteType": "Attack",
          "plural": true,
          "selections": (v3/*: any*/)
        }
      ]
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "weaknesses",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "fleeRate",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "maxCP",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "maxHP",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "evolutions",
      "storageKey": null,
      "args": null,
      "concreteType": "Pokemon",
      "plural": true,
      "selections": [
        (v0/*: any*/),
        (v1/*: any*/)
      ]
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "evolutionRequirements",
      "storageKey": null,
      "args": null,
      "concreteType": "PokemonEvolutionRequirement",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "amount",
          "args": null,
          "storageKey": null
        },
        (v0/*: any*/)
      ]
    }
  ]
};
})());

export {
  Types ,
  Internal ,
  Utils ,
  node ,
  
}
/* fragmentConverter Not a pure module */
