// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as React from "react";
import * as ReactTestingLibrary from "bs-react-testing-library/src/ReactTestingLibrary.bs.js";
import * as App$AppTemplateReasonReact from "../App.bs.js";

Jest.test("renders learn react link", (function (param) {
        return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(ReactTestingLibrary.getByText({
                            HASH: /* Str */4153489,
                            VAL: "Learn React"
                          }, undefined, ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(App$AppTemplateReasonReact.make, {})))));
      }));

export {
  
}
/*  Not a pure module */
