// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as LogoSvg from "./logo.svg";
import * as Pokemons$AppTemplateReasonReact from "./Pokemons.bs.js";

var logo = LogoSvg.default;

import './App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("img", {
                      className: "App-logo",
                      alt: "logo",
                      src: logo
                    }), React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.jsx"), " and save to reload."), React.createElement("a", {
                      className: "App-link",
                      href: "https://reactjs.org",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Learn React")), React.createElement(React.Suspense, {
                  children: React.createElement(Pokemons$AppTemplateReasonReact.make, {}),
                  fallback: React.createElement("div", undefined, "Loading...")
                }));
}

var make = App;

export {
  logo ,
  make ,
  
}
/* logo Not a pure module */
