// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as App$AppTemplateReasonReact from "./App.bs.js";

import './index.css'
;

var root = ReactDOMRe.Experimental.createRootWithId("root");

if (root !== undefined) {
  Caml_option.valFromOption(root).render(React.createElement(App$AppTemplateReasonReact.make, {}));
} else {
  console.log("eRrOR Render with concurrent mode");
}

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  
}
/*  Not a pure module */
