// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$AppTemplateReasonReact from "./App.bs.js";

import './index.css'
;

ReactDOMRe.renderToElementWithId(React.createElement(App$AppTemplateReasonReact.make, {}), "root");

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  
}
/*  Not a pure module */
