// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as Pokemon_fragment_graphql$AppTemplateReasonReact from "./__generated__/Pokemon_fragment_graphql.bs.js";

var convertFragment = Pokemon_fragment_graphql$AppTemplateReasonReact.Internal.convertFragment;

var UseFragment = ReasonRelay.MakeUseFragment({
      fragmentSpec: Pokemon_fragment_graphql$AppTemplateReasonReact.node,
      convertFragment: convertFragment
    });

function use(fRef) {
  return Curry._1(UseFragment.use, fRef);
}

function useOpt(opt_fRef) {
  return Curry._1(UseFragment.useOpt, opt_fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(opt_fRef)) : undefined);
}

var Fragment = {
  Operation: undefined,
  Types: undefined,
  UseFragment: UseFragment,
  use: use,
  useOpt: useOpt
};

export {
  Fragment ,
  
}
/* UseFragment Not a pure module */
