// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as PokemonsQuery_graphql$AppTemplateReasonReact from "./__generated__/PokemonsQuery_graphql.bs.js";
import * as Pokemons_fragment_graphql$AppTemplateReasonReact from "./__generated__/Pokemons_fragment_graphql.bs.js";

var convertFragment = Pokemons_fragment_graphql$AppTemplateReasonReact.Internal.convertFragment;

var UseFragment = ReasonRelay.MakeUseFragment({
      fragmentSpec: Pokemons_fragment_graphql$AppTemplateReasonReact.node,
      convertFragment: convertFragment
    });

function use(fRef) {
  return Curry._1(UseFragment.use, fRef);
}

function useOpt(opt_fRef) {
  return Curry._1(UseFragment.useOpt, opt_fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(opt_fRef)) : undefined);
}

var Fragment = {
  Operation: undefined,
  Types: undefined,
  UseFragment: UseFragment,
  use: use,
  useOpt: useOpt
};

var convertResponse = PokemonsQuery_graphql$AppTemplateReasonReact.Internal.convertResponse;

var convertVariables = PokemonsQuery_graphql$AppTemplateReasonReact.Internal.convertVariables;

var UseQuery = ReasonRelay.MakeUseQuery({
      query: PokemonsQuery_graphql$AppTemplateReasonReact.node,
      convertResponse: convertResponse,
      convertVariables: convertVariables
    });

var use$1 = UseQuery.use;

var Query_makeVariables = PokemonsQuery_graphql$AppTemplateReasonReact.Utils.makeVariables;

var Query_useLoader = UseQuery.useLoader;

var Query_fetch = UseQuery.$$fetch;

var Query_fetchPromised = UseQuery.fetchPromised;

var Query_usePreloaded = UseQuery.usePreloaded;

var Query = {
  Operation: undefined,
  makeVariables: Query_makeVariables,
  Types: undefined,
  UseQuery: UseQuery,
  use: use$1,
  useLoader: Query_useLoader,
  $$fetch: Query_fetch,
  fetchPromised: Query_fetchPromised,
  usePreloaded: Query_usePreloaded
};

function Pokemons(Props) {
  var pokemonListData = Curry._6(use$1, {
        first: 1,
        offset: undefined,
        after: undefined
      }, undefined, undefined, undefined, undefined, undefined);
  console.log(pokemonListData);
  return React.createElement("div", undefined, "Hello");
}

var make = Pokemons;

export {
  Fragment ,
  Query ,
  make ,
  
}
/* UseFragment Not a pure module */
