// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Fetch from "bs-fetch/src/Fetch.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";
import * as RelayRuntime from "relay-runtime";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var Graphql_error = Caml_exceptions.create("RelayEnv-AppTemplateReasonReact.Graphql_error");

function fetchQuery(operation, variables, _cacheConfig) {
  return fetch("https://graphql-pokedex-ihavemind.herokuapp.com/", Fetch.RequestInit.make(/* Post */2, {
                      "content-type": "application/json",
                      accept: "application/json"
                    }, Caml_option.some(JSON.stringify(Js_dict.fromList({
                                  hd: [
                                    "query",
                                    operation.text
                                  ],
                                  tl: {
                                    hd: [
                                      "variables",
                                      variables
                                    ],
                                    tl: /* [] */0
                                  }
                                }))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined)).then(function (resp) {
              if (resp.ok) {
                return resp.json();
              } else {
                return Promise.reject({
                            RE_EXN_ID: Graphql_error,
                            _1: "Request failed: " + resp.statusText
                          });
              }
            });
}

var network = RelayRuntime.Network.create(fetchQuery, undefined);

var environment = ReasonRelay.Environment.make(network, ReasonRelay.Store.make(new RelayRuntime.RecordSource(undefined), undefined, undefined, undefined), undefined, undefined, undefined, undefined);

export {
  Graphql_error ,
  fetchQuery ,
  network ,
  environment ,
  
}
/* network Not a pure module */
